# Generated by Django 5.2.7 on 2025-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='father_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='home_town',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='mother_name',
            field=models.CharField(max_length=50),
        ),
    ]
